export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const SET_ALERT_SHIFTREGISTER = "SET_ALERT_SHIFTREGISTER";
export const REMOVE_ALERT_SHIFTREGISTER = "REMOVE_ALERT_SHIFTREGISTER";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const GET_REPOS = "GET_REPOS";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const POST_ERROR = "POST_ERROR";
export const UPDATE_LIKES = "UPDATE_LIKES";
export const DELETE_POST = "DELETE_POST";
export const ADD_POST = "ADD_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";

export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const USER_ERROR = "USER_ERROR";
export const CLEAR_USER = "CLEAR_USER";
export const DELETE_USER = "DELETE_USER";
export const GET_USER = "GET_USER";
export const GET_USERS = "GET_USERS";

export const GET_JOBS = "GET_JOBS";
export const GET_JOB = "GET_JOB";
export const UPDATE_JOB = "UPDATE_JOB";
export const ADD_JOB = "ADD_JOB";
export const DELETE_JOB = "DELETE_JOB";
export const JOB_ERROR = "JOB_ERROR";
export const CLEAR_JOB = "CLEAR_JOB";

export const GET_BRANCHS = "GET_BRANCHS";
export const GET_BRANCH = "GET_BRANCH";
export const UPDATE_BRANCH = "UPDATE_BRANCH";
export const ADD_BRANCH = "ADD_BRANCH";
export const DELETE_BRANCH = "DELETE_BRANCH";
export const BRANCH_ERROR = "BRANCH_ERROR";
export const CLEAR_BRANCH = "CLEAR_BRANCH";

export const GET_SHIFTS = "GET_SHIFTS";
export const UPDATE_SHIFT = "UPDATE_SHIFT";
export const ADD_SHIFT = "ADD_SHIFT";
export const DELETE_SHIFT = "DELETE_SHIFT";
export const GET_SHIFT = "GET_SHIFT";
export const SHIFT_ERROR = "SHIFT_ERROR";
export const CLEAR_SHIFT = "CLEAR_SHIFT";

export const GET_TYPEUSERS = "GET_TYPEUSERS";
export const UPDATE_TYPEUSER = "UPDATE_TYPEUSER";
export const ADD_TYPEUSER = "ADD_TYPEUSER";
export const DELETE_TYPEUSER = "DELETE_TYPEUSER";
export const TYPEUSER_ERROR = "TYPEUSER_ERROR";
export const CLEAR_TYPEUSER = "CLEAR_TYPEUSER";
export const GET_TYPEUSER = "GET_TYPEUSER";

export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

export const ADD_PERSONINSHIFT = "ADD_PERSONINSHIFT";
export const UPDATE_PERSONINSHIFT = "UPDATE_PERSONINSHIFT";
export const GET_PERSONINSHIFT = "GET_PERSONINSHIFT";
export const PERSONINSHIFT_ERROR = "PERSONINSHIFT_ERROR";
export const CLEAR_PERSONINSHIFT = "CLEAR_PERSONINSHIFT";
export const GET_PERSONINSHIFTS = "GET_PERSONINSHIFTS";
export const GET_PERSONINSHIFTS_PREVWEEK = "GET_PERSONINSHIFTS_PREVWEEK";
export const DELETE_PERSONINSHIFT = "DELETE_PERSONINSHIFT";
export const SETLOADING_PERSONINSHIFT = "SETLOADING_PERSONINSHIFT";

export const GET_SHIFT_REGISTERS = "GET_SHIFT_REGISTERS";
export const UPDATE_SHIFT_REGISTERS = "UPDATE_SHIFT_REGISTERS";
export const ADD_SHIFT_REGISTER = "ADD_SHIFT_REGISTER";
export const DELETE_SHIFT_REGISTER = "DELETE_SHIFT_REGISTER";
export const SHIFT_REGISTER_ERROR = "SHIFT_REGISTER_ERROR";
export const CLEAR_SHIFT_REGISTER = "CLEAR_SHIFT_REGISTER";
export const GET_SHIFT_REGISTER = "GET_SHIFT_REGISTER";
export const CLEAR_SHIFT_REGISTER_VIEW_SALARY = "CLEAR_SHIFT_REGISTER_VIEW_SALARY";
export const SET_CURRENT_DAY = "SET_CURRENT_DAY";

export const GET_NEXTWEEKACTIVE = "GET_NEXTWEEKACTIVE";
export const ADD_NEXTWEEKACTIVE = "ADD_NEXTWEEKACTIVE";
export const DELETE_NEXTWEEKACTIVE = "DELETE_NEXTWEEKACTIVE";
export const NEXTWEEKACTIVE_ERROR = "NEXTWEEKACTIVE_ERROR";
export const CLEAR_NEXTWEEKACTIVE = "CLEAR_NEXTWEEKACTIVE";

export const GET_PERMIT_REGISTS = "GET_PERMIT_REGISTS";
export const UPDATE_PERMIT_REGIST = "UPDATE_PERMIT_REGIST";
export const ADD_PERMIT_REGIST = "ADD_PERMIT_REGIST";
export const DELETE_PERMIT_REGIST = "DELETE_PERMIT_REGIST";
export const PERMIT_REGIST_ERROR = "PERMIT_REGIST_ERROR";
export const CLEAR_PERMIT_REGIST = "CLEAR_PERMIT_REGIST";
export const GET_PERMIT_REGIST = "GET_PERMIT_REGIST";

export const GET_SHIFT_REGISTER_MANAGERS = "GET_SHIFT_REGISTER_MANAGERS";
export const UPDATE_SHIFT_REGISTER_MANAGERS = "UPDATE_SHIFT_REGISTER_MANAGERS";
export const ADD_SHIFT_REGISTER_MANAGERS = "ADD_SHIFT_REGISTER_MANAGERS";
export const DELETE_SHIFT_REGISTER_MANAGERS = "DELETE_SHIFT_REGISTER_MANAGERS";
export const SHIFT_REGISTER_MANAGERS_ERROR = "SHIFT_REGISTER_MANAGERS_ERROR";
export const CLEAR_SHIFT_REGISTER_MANAGERS = "CLEAR_SHIFT_REGISTER_MANAGERS";
export const GET_SHIFT_REGISTER_MANAGER = "GET_SHIFT_REGISTER_MANAGER";
export const SHOW_SHIFTREGISTERS_MODAL = "SHOW_SHIFTREGISTERS_MODAL";
export const SHOW_SHIFTREGISTERS_USER_MODAL = "SHOW_SHIFTREGISTERS_USER_MODAL";
export const SHOW_SHIFTREGISTERS_MANAGER_MODAL = "SHOW_SHIFTREGISTERS_MANAGER_MODAL";
export const SETLOADING_SHIFTREGISTER = "SETLOADING_SHIFTREGISTER";


